export const BULK_ORDER_STATUS = {
  REQUESTED: 'REQUESTED',
  REJECTED: 'REJECTED',
  ACCEPTED: 'ACCEPTED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  SCHEDULED: 'SCHEDULED',
  ASSIGNED: 'ASSIGNED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const BULK_ORDER_EVENT_TYPES = {
  BIRTHDAY: 'Birthday',
  CORPORATE: 'Corporate',
  WEDDING: 'Wedding',
  PARTY: 'Party',
  OTHER: 'Other',
};
