export const ORDER_STATUS = {
  // Bulk order specific
  REQUESTED: 'REQUESTED',
  REJECTED: 'REJECTED',
  ACCEPTED: 'ACCEPTED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  SCHEDULED: 'SCHEDULED',
  ASSIGNED: 'ASSIGNED',
  
  // Common statuses
  PLACED: 'PLACED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const ORDER_TYPE = {
  SINGLE: 'SINGLE',
  BULK: 'BULK',
};
